@startuml MedalPusher

namespace Case{
    class PusherMover
}

namespace Item{
    interface IReadOnlyFieldItem
    interface IFieldItem
    class FieldItem
    IReadOnlyFieldItem <|-- IFieldItem
    IFieldItem <|.. FieldItem

    interface IReadOnlyMedal
    interface IMedal
    class Medal
    IReadOnlyMedal <|-- IMedal
    IMedal <|.. Medal

    interface IFieldObject
    IFieldObject <|-- IMedal
    IFieldObject <|-- IFieldItem
    
    namespace Checker{
        interface IObservableItemChecker<TItem>{
            +IObservable<TItem>
        }

        interface IObservableMedalChecker{
            +IObservable<IMedal>
        }
        class MedalChecker
        IObservableItemChecker <|-- IObservableMedalChecker
        IObservableMedalChecker <|.. MedalChecker

        interface IObservableFieldItemChecker{
            +IObservable<IFieldItem>
        }
        class FieldItemChecker
        IObservableItemChecker <|-- IObservableFieldItemChecker
        IObservableFieldItemChecker <|.. FieldItemChecker
    }
    
    namespace Payout{
        interface IObservableMedalPayouter{
            +IObservable<Unit> InputedMedalCount
        }
        interface IMedalPayoutOperator{
            +void Payout(int);
        }
        class MedalPayouter
        MedalPayouter .|> IMedalPayoutOperator
        IObservableMedalPayouter <|.. MedalPayouter

        class PayoutMedalView<<View>>
        PayoutMedalView --> IObservableMedalPayouter : 払い出しメダル数を監視

    }
    
    namespace Inventory{
        interface IObservableMedalInventory{
            +IObservable<int> MedalInventoryCount
        }
        class MedalInventory{
            -ReactiveProperty<int> m_medalCount
        }
        IObservableMedalInventory <|.. MedalInventory

        interface IObservableFieldItemInventory{
            +IObservable<IReadOnlyList<IFieldItem>> 
        }
        class FieldItemInventory{
            -ReactiveCollection<IFieldItem> m_items
        }
        IObservableFieldItemInventory <|.. FieldItemInventory

        MedalInventory ---> Item.Checker.IObservableMedalChecker : 落ちたメダルを監視
        FieldItemInventory ---> Item.Checker.IObservableFieldItemChecker : 落ちたアイテムを監視
        Input.IInoutProvider <--- MedalInventory : 入力を監視

        class FieldItemApplyer
        Item.Payout.IMedalPayoutOperator <-- FieldItemApplyer : メダル払い出しを要求

        class MedalInventoryView<<View>>
        MedalInventoryView --> IObservableMedalInventory
        class FieldItemInventoryView<<View>>
        FieldItemInventoryView --> IObservableFieldItemInventory

        FieldItemApplyer --> IObservableFieldItemInventory
        MedalInventory --> Item.Payout.IMedalPayoutOperator : メダル払い出しを要求
    }

    ' Item.Inventory.IObservableMedalCounter <- PayoutMedalView : 落下メダル数を監視
    ' Item.Payout.IObservableMedalPayouter <- PayoutMedalView : 投入メダル数を監視
}

namespace Input{
    interface IInoutProvider
    class UserInputProvider
    class AutoInputProvider
    class Input<<static>>
    IInoutProvider <|.. UserInputProvider
    IInoutProvider <|.. AutoInputProvider
    UserInputProvider --> Input
}

namespace Slot{
    class StockManager
    IObservableStockCount <|.. StockManager
    Item.Checker.IObservableMedalChecker <- StockManager : チェッカーを監視
    class Slot
    enum SlotStatus{
        Idol
        Rolling
    }
    IObservableStockCount <-- Slot : ストック数を監視

    ' ISlot <|.. Slot
    SlotStatus <- Slot

    interface IObservableStockCount{
        +ObservableStockCount { get; }
    }

    class StockView<<View>>
    IObservableStockCount <- StockView : ストックを監視

}


@enduml